verbose: false

#Интеграция с MythicDungeons
MDSupport: true

commands_name:
  - party
  - party_a

#ОТКЛЮЧЕННО
#Включение поддержки прокси
#Для верной работы требуется:
#spigot.yml -> bungeecord = true; даже для velocity
#в конфиге velocity обязательно bungee-plugin-message-channel = true
proxy_support: false

#ОТКЛЮЧЕННО
#Необходимо для синхронизации команд между серверами
#Необязательно при выключенном прокси
mysql:
  username:
  password:
  url:
  name:

global_max_limit: 3

#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
#название_команды: название_звука громкость питч
sound_notification:
  invite:
  invite_accepted_inviter:
  invite_accepted_invited:
  invite_refused_inviter:
  invite_refused_invited:
  kick:
  disband:
  slotplayer:
  help:

timers:
  invite: 1800
  leader: 3600
  participant: 3600
  disband: true

command_trigger:
  party_help:
    commands:
    commands_fail:
  party_leave:
    commands:
    commands_fail:
  party_invite:
    commands:
    commands_fail:
  party_givelead:
    commands:
    commands_fail:
  party_kick:
    commands:
    commands_fail:
  party_disband:
    commands:
    commands_fail:
  party_slotplayer:
    commands:
    commands_fail:
  part_accept:
    commands:
    commands_fail:
  party_refuse:
    commands:
    commands_fail:
  party_a_teleport:
    commands:
    commands_fail:
  party_a_command:
    commands:
    commands_fail: