verbose: false

commands_name:
  - party
  - party_a

global_max_limit: 3

#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
#название_команды: название_звука громкость питч
sound_notification:
  invite:
  invite_accepted:
  invite_is_not_accepted:
  kick:
  disband:
  slotplayer:
  help:

timer_to_kick:
  leader: 3600
  participant: 3600
  disband: true

command_trigger:
  party_help:
    commands:
    commands_fail:
  party_leave:
    commands:
    commands_fail:
  party_invite:
    commands:
    commands_fail:
  party_givelead:
    commands:
    commands_fail:
  party_kick:
    commands:
    commands_fail:
  party_disband:
    commands:
    commands_fail:
  party_slotplayer:
    commands:
    commands_fail:
  part_accept:
    commands:
    commands_fail:
  party_refuse:
    commands:
    commands_fail:
  party_a_teleport:
    commands:
    commands_fail:
  party_a_command:
    commands:
    commands_fail: